"use strict";

// Contenido real del sitio: guías de compra y artículos de blog.
// Nada de datos de producto inventados (ni precios exactos, ni valoraciones,
// ni modelos) en el cuerpo de la guía: son guías de criterio, no fichas de
// producto. Los productos concretos van en el array `products` de cada guía,
// verificados uno a uno en Amazon.es (ASIN, precio, valoración e imagen reales
// en la fecha de la guía).

const GUIDES = [
  {
    slug: "arneses-para-perros",
    title: "Cómo elegir un arnés para perro",
    dek: "Antitirones, de paseo o táctico: qué mirar según el tamaño y el carácter de tu perro antes de comprar.",
    updated: "2026-09-16",
    img: "/assets/img/guias/arneses-para-perros.jpg",
    intro: [
      "Un arnés mal elegido no solo incomoda a tu perro: puede rozarle las axilas, dejarle escapar en un susto o no servir de nada si tira fuerte de la correa. Acertar depende más de la forma del arnés y del ajuste que del precio.",
      "Esta guía no recomienda un modelo concreto: te da los criterios para comparar cualquier arnés, incluidos los que encuentres en Amazon.",
    ],
    sections: [
      {
        heading: "Arnés en H, en Y o de tipo chaleco",
        body: [
          "El arnés en H (dos tiras que cruzan el pecho y la espalda) es el más ligero y barato, buena opción para perros tranquilos que no tiran. El arnés en Y deja libre el movimiento de los hombros porque no cruza el pecho en horizontal, lo que lo hace más recomendable para razas pequeñas o con problemas de tráquea.",
          "El arnés tipo chaleco reparte la presión en una superficie mayor de malla acolchada, es el más cómodo para paseos largos y el que mejor tolera un perro nervioso, pero abriga más en verano y pesa algo más que los otros dos formatos.",
        ],
      },
      {
        heading: "Antitirones: cómo funciona de verdad",
        body: [
          "Los arneses antitirones tienen la anilla de enganche en el pecho, no en la espalda: cuando el perro tira hacia delante, la propia tracción le gira el cuerpo hacia el dueño en lugar de dejarle avanzar. No es un arnés que \"frene\" físicamente, así que sigue haciendo falta trabajar la educación en la correa, pero ayuda mucho mientras se entrena.",
          "Los arneses con doble anilla (pecho y espalda) dan más margen: espalda para paseos tranquilos, pecho para reforzar el control cuando hace falta, sin tener que cambiar de arnés.",
        ],
      },
      {
        heading: "Tallaje: por qué no basta con el peso del perro",
        body: [
          "Las tablas de talla por peso son solo una referencia orientativa: dos perros del mismo peso pueden tener un contorno de pecho muy distinto según la raza. Mide el contorno del pecho (la parte más ancha, justo detrás de las patas delanteras) y el contorno del cuello antes de elegir talla, y compara con la tabla específica de cada fabricante, no con una tabla genérica.",
          "Un arnés bien ajustado deja pasar dos dedos entre la tira y el cuerpo del perro, ni más (se puede escapar) ni menos (le roza al moverse).",
        ],
      },
      {
        heading: "Material, transpirabilidad y seguridad",
        body: [
          "La malla transpirable reduce el sobrecalentamiento en paseos largos o en verano, algo especialmente importante en razas braquicéfalas (bulldog, carlino) que ya regulan peor el calor. Las tiras reflectantes son un extra barato que aporta seguridad real en paseos al anochecer.",
          "Revisa que las hebillas sean de plástico resistente o metal, no de plástico fino que pueda partirse con un tirón fuerte, y que el arnés tenga un asa de agarre en la espalda si necesitas controlar al perro de cerca en momentos puntuales (cruzar una calle, subir a un coche).",
        ],
      },
    ],
    checklist: [
      "Forma según el perro: en H para tranquilos, en Y para hombros libres, chaleco para más comodidad",
      "Anilla de enganche en el pecho si necesitas efecto antitirones",
      "Medida real de contorno de pecho y cuello, no solo el peso",
      "Malla transpirable si el perro pasea mucho o vive en clima cálido",
      "Hebillas resistentes y, si te interesa, asa de agarre en la espalda",
    ],
    faq: [
      {
        q: "¿Arnés o collar para pasear a diario?",
        a: "El arnés reparte la fuerza en el pecho y la espalda en lugar de concentrarla en el cuello, así que es la opción más segura para el uso diario, sobre todo en perros que tiran o en razas con la tráquea sensible. El collar sigue siendo necesario para llevar la chapa identificativa, pero para pasear se recomienda el arnés.",
      },
      {
        q: "¿Los arneses antitirones son crueles?",
        a: "No: no aprietan ni hacen daño, simplemente cambian el punto de enganche para que la fuerza del tirón gire el cuerpo del perro en lugar de dejarle avanzar en línea recta. Son una herramienta de apoyo mientras se trabaja la educación en la correa, no un castigo.",
      },
    ],
    products: [
      {
        asin: "B0DV9M966C",
        title: "Trixie Arnés Premium para Perros, S-M, 42-60 cm",
        note: "Entrada de gama de una marca especializada, ajuste sencillo en tres puntos.",
        img: "https://m.media-amazon.com/images/I/61hDQtM5uZL._AC_UL320_.jpg",
        price: "9,99",
        rating: "4,6★",
      },
      {
        asin: "B0FH6J96LC",
        title: "OFFCUP Arnés y Correa para Perro, Antitirones, Malla Transpirable",
        note: "Incluye correa a juego; buena opción de entrada para perros pequeños y cachorros.",
        img: "https://m.media-amazon.com/images/I/61QYzuTWAzL._AC_UL320_.jpg",
        price: "11,99",
        rating: "4,2★",
      },
      {
        asin: "B01M8JT6FT",
        title: "rabbitgoo Arnés Perro Grande Mediano Pequeño, Antitirones, Reflectante",
        note: "El más vendido de la categoría; malla acolchada y tiras reflectantes en varias tallas.",
        img: "https://m.media-amazon.com/images/I/61x25BTRT6L._AC_UL320_.jpg",
        price: "17,76",
        rating: "4,5★",
      },
      {
        asin: "B075FRGCT1",
        title: "Eagloo Arnés Perro Grande Mediano, Antitirones, Chaleco Acolchado Ajustable",
        note: "Formato chaleco con anillos de pecho y espalda para alternar según el paseo.",
        img: "https://m.media-amazon.com/images/I/712yOtMPqZL._AC_UL320_.jpg",
        price: "19,99",
        rating: "4,5★",
      },
      {
        asin: "B0CQX4HFL8",
        title: "rabbitgoo Arnés Perro Mediano con 3 Hebillas y Clip Frontal",
        note: "Liberación rápida en el cuello, útil para perros que se agobian al vestirse.",
        img: "https://m.media-amazon.com/images/I/711fAkQPaGL._AC_UL320_.jpg",
        price: "21,99",
        rating: "4,5★",
      },
      {
        asin: "B09B6BKPS8",
        title: "haapaw Arnés para Perro sin Tirar, Ajustable, Reflectante Oxford",
        note: "Tejido Oxford resistente para perros medianos y grandes con tendencia a tirar.",
        img: "https://m.media-amazon.com/images/I/81VCpAccdTL._AC_UL320_.jpg",
        price: "26,99",
        rating: "4,6★",
      },
      {
        asin: "B09ZPJVCZ5",
        title: "OneTigris Aire Mesh Arnés Táctico Sin Tirones, Malla Transpirable Militar",
        note: "Gama alta: construcción táctica con asas reforzadas para perros muy activos.",
        img: "https://m.media-amazon.com/images/I/71nGxdWcMmL._AC_UL320_.jpg",
        price: "50,99",
        rating: "4,5★",
      },
      {
        asin: "B00A9XBMEG",
        title: "JULIUS-K9 Arnés IDC, 0/M-L, 58-76cm/40mm, Camuflaje",
        note: "Marca profesional usada en cuerpos de seguridad; asa superior reforzada y anilla en el lomo para agarre firme.",
        img: "https://m.media-amazon.com/images/I/71M-MiUjNWL._AC_UL320_.jpg",
        price: "27,99",
        rating: "4,7★",
      },
      {
        asin: "B0BL3NJPT9",
        title: "Amazon Basics Arnés sin Tirones, Ajustable, Acolchado, Talla Grande",
        note: "Alternativa económica de marca propia de Amazon, con tiras reflectantes y buen acabado para el precio.",
        img: "https://m.media-amazon.com/images/I/61zuTjczm+L._AC_UL320_.jpg",
        price: "15,19",
        rating: "4,4★",
      },
      {
        asin: "B0FDKT9ZBN",
        title: "rabbitgoo Arnés Perro Pequeño, Ligero, Suave y Transpirable",
        note: "Versión ligera de rabbitgoo pensada específicamente para perros pequeños y cachorros.",
        img: "https://m.media-amazon.com/images/I/71HYkVSv6TL._AC_UL320_.jpg",
        price: "10,79",
        rating: "4,6★",
      },
      {
        asin: "B097247ZB5",
        title: "PoyPet Arnés Antitirones con Asa y Clip Frontal, Reflectante",
        note: "Buen equilibrio precio-control, con asa superior para sujeción rápida en momentos puntuales.",
        img: "https://m.media-amazon.com/images/I/71sfRpIaRVL._AC_UL320_.jpg",
        price: "22,79",
        rating: "4,5★",
      },
    ],
  },
  {
    slug: "correas-para-perros",
    title: "Cómo elegir una correa para perro",
    dek: "Fija, extensible o multifunción: qué formato de correa compensa según cómo paseas a tu perro.",
    updated: "2026-09-15",
    img: "/assets/img/guias/correas-para-perros.jpg",
    intro: [
      "La correa parece lo más simple del equipo de paseo, pero el formato equivocado es la causa habitual de tirones al hombro, enganches con otros perros o sustos con el tráfico. El mejor formato depende del sitio donde pasees y del nivel de control que necesites, no de cuál sea \"la más resistente\".",
    ],
    sections: [
      {
        heading: "Correa fija frente a correa extensible",
        body: [
          "Las correas fijas (1,2-2 m) dan el control más directo y predecible: útiles en ciudad, cerca del tráfico o en zonas con otros perros, porque la distancia no varía. Las correas extensibles (retráctiles) permiten más libertad de movimiento en zonas abiertas, pero reducen el control inmediato y no son recomendables cerca de carreteras o en aceras estrechas.",
          "Muchas asociaciones de adiestramiento desaconsejan la extensible como correa única: es buena como complemento en parque o campo, no como sustituto de una correa fija para el día a día.",
        ],
      },
      {
        heading: "Longitud según el uso",
        body: [
          "Una correa de 1,2 m es la más manejable en ciudad y en espacios con mucha gente. Las de 1,8-2 m dan algo más de margen sin perder control, buenas para paseos tranquilos. Las correas largas (3-10 m) están pensadas para trabajo de llamada y adiestramiento en espacios abiertos, no para paseo normal.",
        ],
      },
      {
        heading: "Material y grosor según el tamaño del perro",
        body: [
          "El nailon es el material más común: ligero, resistente y barato, aunque puede desgastarse si el perro tira con fuerza constante. Las correas de cuero curten mejor con el uso y son más suaves con la mano, pero pesan más y necesitan algo de mantenimiento. Cuanto mayor sea el tamaño y la fuerza del perro, más ancha debe ser la cinta: una correa fina en un perro grande se nota enseguida en la resistencia al tirón.",
        ],
      },
      {
        heading: "Mango, enganches y detalles que se notan con el uso",
        body: [
          "Un mango acolchado marca la diferencia en paseos largos o con perros que tiran, evitando rozaduras en la mano. Los mosquetones de metal resistente son más fiables que los de plástico, sobre todo si el perro es fuerte. Las correas con doble enganche (dos mosquetones en distintos puntos) permiten pasear a dos perros o cambiar de punto de sujeción sin cambiar de correa.",
        ],
      },
    ],
    checklist: [
      "Fija para uso diario en ciudad; extensible solo como complemento en zonas abiertas",
      "Longitud de 1,2-2 m para paseo normal, más larga solo para adiestramiento",
      "Grosor de la cinta proporcional a la fuerza del perro",
      "Mango acolchado si el perro tira o el paseo es largo",
      "Mosquetones de metal resistente, no de plástico fino",
    ],
    faq: [
      {
        q: "¿Es segura la correa extensible en ciudad?",
        a: "No es la opción más segura cerca de tráfico, cruces o aceras estrechas: el mecanismo tarda en frenar y reduce el control inmediato sobre el perro. Funciona mejor en parques o zonas abiertas sin coches ni otros perros cerca.",
      },
      {
        q: "¿Qué longitud de correa necesito para pasear en ciudad?",
        a: "Entre 1,2 y 2 metros es lo habitual para paseo urbano: da margen de movimiento sin perder el control en cruces, portales o al pasar junto a otros perros.",
      },
    ],
    products: [
      {
        asin: "B0GVJFTT4T",
        title: "REVER Correa para Perros Nailon Trenzado Reflectante, Mango Ergonómico",
        note: "Entrada de gama: nailon trenzado resistente con buen precio por metro.",
        img: "https://m.media-amazon.com/images/I/71uqJmg6sVL._AC_UL320_.jpg",
        price: "6,99",
        rating: "4,5★",
      },
      {
        asin: "B095C7V817",
        title: "Taglory Correa Antitirones 1,5m, Mango Acolchado",
        note: "Mango acolchado pensado para perros medianos y grandes que tiran.",
        img: "https://m.media-amazon.com/images/I/71oitvj9Y6L._AC_UL320_.jpg",
        price: "9,99",
        rating: "4,6★",
      },
      {
        asin: "B0B59GWVJ9",
        title: "Edipets Correa Extensible Retráctil 5m, 360º Sin Enredos",
        note: "Extensible como complemento para parque o campo, no para uso en ciudad.",
        img: "https://m.media-amazon.com/images/I/61eelMcS3GL._AC_UL320_.jpg",
        price: "8,99",
        rating: "4,6★",
      },
      {
        asin: "B00O3B2RG2",
        title: "flexi Classic S Correa Retráctil de Cinta 5m, perros hasta 15 kg",
        note: "Marca de referencia en correas retráctiles, mecanismo de frenado fiable.",
        img: "https://m.media-amazon.com/images/I/71LjBOHiamS._AC_UL320_.jpg",
        price: "11,19",
        rating: "4,6★",
      },
      {
        asin: "B00589G9YY",
        title: "Halti Correa de Adiestramiento Multifunción con Doble Enganche",
        note: "Doble enganche: útil para pasear a dos alturas o dos perros con la misma correa.",
        img: "https://m.media-amazon.com/images/I/71wn-nmzZYL._AC_UL320_.jpg",
        price: "12,49",
        rating: "4,6★",
      },
      {
        asin: "B0DZC2PD6L",
        title: "Correa para Perro Manos Libres con Riñonera y Doble Asa",
        note: "Formato manos libres con riñonera, pensado para correr o hacer canicross.",
        img: "https://m.media-amazon.com/images/I/71bQcs-aapL._AC_UL320_.jpg",
        price: "16,99",
        rating: "4,4★",
      },
      {
        asin: "B08XQC4WNG",
        title: "Correa Perro Larga 10m, Nylon y Metal, Asa Acolchada",
        note: "Gama larga para trabajo de llamada y adiestramiento en espacios abiertos.",
        img: "https://m.media-amazon.com/images/I/61aXaKmHe6L._AC_UL320_.jpg",
        price: "10,99",
        rating: "4,5★",
      },
      {
        asin: "B012H63A5Q",
        title: "Correa de Control para Perros Halti, 2 Metros",
        note: "Pensada para trabajo de adiestramiento, complementa al arnés o collar Halti de la misma marca.",
        img: "https://m.media-amazon.com/images/I/71pumw+njbL._AC_UL320_.jpg",
        price: "10,96",
        rating: "4,6★",
      },
      {
        asin: "B01HDAX59W",
        title: "flexi Classic L Cinta 8m, Correa Extensible para Perros hasta 50kg",
        note: "Versión de mayor capacidad de flexi, pensada para perros grandes de hasta 50 kg.",
        img: "https://m.media-amazon.com/images/I/7176gzxZqyS._AC_UL320_.jpg",
        price: "23,21",
        rating: "4,6★",
      },
      {
        asin: "B08CVHHKKD",
        title: "Taglory Correa Anti Tirones 1,2m, Mango Acolchado",
        note: "Versión más corta de Taglory, cómoda para paseos en zonas con mucha gente.",
        img: "https://m.media-amazon.com/images/I/81D0hkOSpHL._AC_UL320_.jpg",
        price: "8,99",
        rating: "4,6★",
      },
      {
        asin: "B0GGWTS5HQ",
        title: "X XBEN Correa Reflectante con Mango Acolchado, Varias Longitudes",
        note: "Disponible en varias longitudes desde el mismo modelo, fácil de ajustar al uso que le vayas a dar.",
        img: "https://m.media-amazon.com/images/I/81Azwb+SgAL._AC_UL320_.jpg",
        price: "9,99",
        rating: "4,6★",
      },
    ],
  },
  {
    slug: "comederos-automaticos-para-mascotas",
    title: "Comederos automáticos para perros y gatos: guía de compra",
    dek: "Capacidad, control de raciones y limpieza: lo que de verdad marca la diferencia en un comedero automático.",
    updated: "2026-09-14",
    img: "/assets/img/guias/comederos-automaticos-para-mascotas.jpg",
    intro: [
      "Un comedero automático soluciona horarios irregulares y dietas con raciones controladas, pero no todos valen para el mismo caso: un dispensador pensado para un gato solo no sirve igual para dos perros grandes con distinto apetito.",
    ],
    sections: [
      {
        heading: "Capacidad y número de mascotas",
        body: [
          "La capacidad del depósito (en litros) determina cuántos días puede funcionar sin recarga: 3-4 litros suelen bastar para un gato o un perro pequeño durante 1-2 semanas, mientras que perros grandes o varias mascotas necesitan depósitos de 6 litros o más. Si tienes más de una mascota que come a ritmos distintos, un comedero con doble tolva evita que uno le quite la comida al otro.",
        ],
      },
      {
        heading: "Control de raciones y programación",
        body: [
          "Los comederos con control por app permiten programar el número de comidas al día y el tamaño de cada ración con más precisión que un temporizador mecánico, útil si la mascota necesita una dieta controlada por el veterinario. Cuantos más horarios personalizables permita, mejor se adapta a rutinas irregulares (turnos de trabajo, fin de semana distinto entre semana).",
        ],
      },
      {
        heading: "Alimento seco frente a pienso húmedo o mixto",
        body: [
          "La mayoría de comederos automáticos están diseñados solo para pienso seco: el mecanismo de tornillo sinfín se atasca con comida húmeda. Si tu mascota come pienso húmedo o mixto, necesitas un modelo específico con compartimentos refrigerados o bandejas separadas, no un dispensador genérico de pienso seco.",
        ],
      },
      {
        heading: "Facilidad de limpieza y alimentación de emergencia",
        body: [
          "Un comedero con tolva y bol desmontables se limpia mucho más rápido que uno con piezas fijas, y evita que la grasa del pienso se acumule y enrancie. Fíjate también en si funciona con pilas además de con cable: un corte de luz no debería dejar a la mascota sin comer si sales varios días.",
        ],
      },
    ],
    checklist: [
      "Capacidad del depósito según el número de días sin recarga que necesitas",
      "Doble tolva si tienes más de una mascota",
      "Control por app si necesitas programar raciones con precisión",
      "Comprobar que admite el tipo de alimento que das (seco, húmedo o mixto)",
      "Piezas desmontables para limpiar y alimentación por pilas de respaldo",
    ],
    faq: [
      {
        q: "¿Puedo usar un comedero automático con pienso húmedo?",
        a: "La mayoría no: están pensados para pienso seco porque usan un tornillo sinfín que se atasca con comida húmeda. Si necesitas dispensar húmedo, busca modelos específicos con compartimentos refrigerados para varias comidas al día.",
      },
      {
        q: "¿Qué pasa si se va la luz con un comedero automático?",
        a: "Depende del modelo: los que funcionan también con pilas mantienen la programación y siguen dispensando aunque se corte la corriente. Es un criterio a comprobar antes de comprar si vas a dejar sola a la mascota varios días.",
      },
    ],
    products: [
      {
        asin: "B0FM71H4PZ",
        title: "Nobleza Comedero Bebedero Automático 2 en 1, Antiderrames",
        note: "Entrada de gama: combina comida y agua en un solo dispensador compacto.",
        img: "https://m.media-amazon.com/images/I/61APbZEDKZL._AC_UL320_.jpg",
        price: "21,99",
        rating: "3,8★",
      },
      {
        asin: "B09QXGHRM4",
        title: "Edipets Dispensador Automático Comida y Agua, Pack 2 Unidades 3,8L",
        note: "Dos unidades independientes, útil si tienes gato y perro con horarios distintos.",
        img: "https://m.media-amazon.com/images/I/81oRKraIU6L._AC_UL320_.jpg",
        price: "29,99",
        rating: "4,4★",
      },
      {
        asin: "B0DJKV88PY",
        title: "Anykuu Comedero Automático 4L, 1-6 Comidas, Grabación de Voz",
        note: "Permite grabar un mensaje de voz para llamar a la mascota a comer.",
        img: "https://m.media-amazon.com/images/I/71lV-ZnixUL._AC_UL320_.jpg",
        price: "33,99",
        rating: "4,3★",
      },
      {
        asin: "B09CPPPPTS",
        title: "Faroro Comedero Automático 7L con Temporizador, hasta 5 Comidas al Día",
        note: "Depósito grande de 7L: buena autonomía para ausencias de varios días.",
        img: "https://m.media-amazon.com/images/I/61JHrHa1xPL._AC_UL320_.jpg",
        price: "39,99",
        rating: "4,4★",
      },
      {
        asin: "B0CD7NRW37",
        title: "PETKIT Comedero Automático WiFi 3L, Control App, 1-10 Comidas al Día",
        note: "Control fino de raciones vía app, hasta 10 comidas diarias programables.",
        img: "https://m.media-amazon.com/images/I/61YV-DxpRML._AC_UL320_.jpg",
        price: "66,49",
        rating: "4,4★",
      },
      {
        asin: "B0H1KYPFXM",
        title: "Comedero Automático para Razas Grandes, 15L de Capacidad",
        note: "Pensado para perros grandes o varias mascotas: máxima capacidad de la selección.",
        img: "https://m.media-amazon.com/images/I/61lwmaQpu2L._AC_UL320_.jpg",
        price: "123,49",
        rating: "4,5★",
      },
      {
        asin: "B0DMNN1PHL",
        title: "PETKIT Comedero Automático con Cámara 1080P, App, 3L",
        note: "Gama alta: cámara integrada para ver y hablar con la mascota a distancia.",
        img: "https://m.media-amazon.com/images/I/61nbDboUMJL._AC_UL320_.jpg",
        price: "149,99",
        rating: "4,5★",
      },
      {
        asin: "B0DRCQV8LY",
        title: "Comedero Automático Comida Húmeda, Temporizador Programable y Refrigerado",
        note: "Uno de los pocos pensados específicamente para pienso húmedo, con compartimento refrigerado.",
        img: "https://m.media-amazon.com/images/I/71Mlb0O5PdL._AC_UL320_.jpg",
        price: "69,99",
        rating: "4,1★",
      },
      {
        asin: "B0C2J7JXZ4",
        title: "PETLIBRO Comedero Automático WiFi 5L, Sensor y Bloqueo de Comida Baja",
        note: "Marca alternativa a PETKIT, con aviso de nivel bajo de comida y mayor capacidad de depósito.",
        img: "https://m.media-amazon.com/images/I/617ca71YbFL._AC_UL320_.jpg",
        price: "97,99",
        rating: "4,0★",
      },
      {
        asin: "B0CMCVNPN2",
        title: "Balimo Comedero Automático WiFi 3L, Control App, 10 Comidas al Día",
        note: "Opción económica con control por app, hasta 10 comidas programables al día.",
        img: "https://m.media-amazon.com/images/I/61Jt5osZawL._AC_UL320_.jpg",
        price: "36,99",
        rating: "4,5★",
      },
      {
        asin: "B0GSZ7CWWH",
        title: "PETKIT Comedero con Cámara, Reconocimiento de Varios Gatos",
        note: "Gama alta: reconoce a cada gato, útil en casas con más de una mascota y horarios distintos.",
        img: "https://m.media-amazon.com/images/I/71CgQbAUhpL._AC_UL320_.jpg",
        price: "132,99",
        rating: "4,3★",
      },
    ],
  },
  {
    slug: "fuentes-de-agua-para-mascotas",
    title: "Fuentes de agua para perros y gatos: qué mirar antes de comprar",
    dek: "Caudal, capacidad y nivel de ruido: por qué muchas mascotas beben más con una fuente que con un bol.",
    updated: "2026-09-13",
    img: "/assets/img/guias/fuentes-de-agua-para-mascotas.jpg",
    intro: [
      "Muchos gatos beben menos de lo que deberían porque el agua quieta de un bol no les atrae tanto como el agua en movimiento: una fuente puede ser la diferencia entre una mascota bien hidratada y una con riesgo de problemas urinarios. Pero no todas las fuentes sirven igual para todos los casos.",
    ],
    sections: [
      {
        heading: "Por qué una fuente frente a un bol normal",
        body: [
          "El movimiento del agua imita fuentes naturales y estimula el instinto de beber de gatos y perros, además de oxigenar el agua y evitar que se estanque tan rápido como en un bol. Es un cambio especialmente recomendable en gatos, con más tendencia a beber poco, y en mascotas mayores o con antecedentes de problemas renales o urinarios (siempre bajo indicación veterinaria).",
        ],
      },
      {
        heading: "Capacidad y autonomía",
        body: [
          "Las fuentes de 1,5-2,5 litros bastan para un gato o un perro pequeño con recargas cada 1-2 días. Para perros medianos o grandes, o para varias mascotas, conviene una capacidad de 3 litros o más para no tener que rellenar a diario.",
        ],
      },
      {
        heading: "Filtro y nivel de ruido",
        body: [
          "El filtro de carbón activo reduce el sabor a cloro y las impurezas del agua del grifo, y hay que cambiarlo cada 2-4 semanas según el uso para que siga siendo eficaz. El nivel de ruido de la bomba importa más de lo que parece: una fuente ruidosa puede espantar a gatos asustadizos justo cuando se acercan a beber, así que las bombas ultrasilenciosas son preferibles aunque cuesten algo más.",
        ],
      },
      {
        heading: "Material y facilidad de limpieza",
        body: [
          "El acero inoxidable no retiene bacterias ni olores como el plástico, y es más fácil de mantener limpio a largo plazo, aunque cuesta algo más que las fuentes de plástico o cerámica. Sea cual sea el material, hay que limpiar la fuente completa (no solo cambiar el agua) al menos una vez por semana para evitar la película de biofilm que se forma en superficies húmedas.",
        ],
      },
    ],
    checklist: [
      "Capacidad según el número de mascotas y la frecuencia de recarga que quieras",
      "Filtro de carbón activo reemplazable cada 2-4 semanas",
      "Bomba silenciosa, sobre todo si el gato es asustadizo",
      "Acero inoxidable si priorizas higiene a largo plazo sobre precio",
      "Limpieza completa semanal, no solo rellenar agua",
    ],
    faq: [
      {
        q: "¿Mi gato necesita de verdad una fuente de agua?",
        a: "No es obligatorio, pero ayuda mucho en gatos que beben poco de forma natural: el agua en movimiento estimula el instinto de beber más que un bol quieto. Si tu gato ya bebe bien de un bol, una fuente es una mejora, no una necesidad urgente.",
      },
      {
        q: "¿Cada cuánto hay que cambiar el filtro?",
        a: "Como referencia general, cada 2-4 semanas según el número de mascotas y la dureza del agua de tu zona. Un filtro saturado deja de retener impurezas y puede empezar a soltar lo que ya ha absorbido, así que conviene no alargar demasiado el cambio.",
      },
    ],
    products: [
      {
        asin: "B0CSCVBB38",
        title: "Fuente Automática 2,2L con Bomba Ultrasilenciosa y Filtro de Carbón Activo",
        note: "Entrada de gama con bomba silenciosa, buena opción para gatos asustadizos.",
        img: "https://m.media-amazon.com/images/I/61ekJbPqjFL._AC_UL320_.jpg",
        price: "15,24",
        rating: "4,2★",
      },
      {
        asin: "B0GXTF5MWS",
        title: "Fuente de Agua 2,2L con Indicador LED y Triple Filtración",
        note: "Indicador LED de nivel de agua, útil para no quedarse sin agua sin darte cuenta.",
        img: "https://m.media-amazon.com/images/I/61RFAfI4b3L._AC_UL320_.jpg",
        price: "20,75",
        rating: "4,8★",
      },
      {
        asin: "B0F5BF98CW",
        title: "Fuente para Gatos Acero Inoxidable 2,6L",
        note: "Acero inoxidable: más fácil de mantener limpia a largo plazo que el plástico.",
        img: "https://m.media-amazon.com/images/I/7190ACZVWVL._AC_UL320_.jpg",
        price: "26,99",
        rating: "4,4★",
      },
      {
        asin: "B0FF48X5N8",
        title: "FEELNEEDY Fuente 2,8L Acero Inoxidable con 3 Filtros, Ultra Silenciosa",
        note: "Sistema de tres filtros para agua más limpia en hogares con varias mascotas.",
        img: "https://m.media-amazon.com/images/I/714bGG3GHbL._AC_UL320_.jpg",
        price: "22,79",
        rating: "4,2★",
      },
      {
        asin: "B0B4W8FDBV",
        title: "PETKIT EVERSWEET Fuente 2L, Bomba Inalámbrica, Control por App",
        note: "Bomba inalámbrica y control por app: avisa cuándo toca cambiar el filtro.",
        img: "https://m.media-amazon.com/images/I/61wmy5X3zsL._AC_UL320_.jpg",
        price: "55,99",
        rating: "4,5★",
      },
      {
        asin: "B0FGQDWFKN",
        title: "Sibays Bebedero 15L para Perro Grande, Ventana Visible y LED",
        note: "Pensada para perros grandes: gran capacidad para no rellenar a diario.",
        img: "https://m.media-amazon.com/images/I/7125TNa-pVL._AC_UL320_.jpg",
        price: "69,99",
        rating: "4,4★",
      },
      {
        asin: "B0FJFDPZ6X",
        title: "PETKIT EVERSWEET MAX 2 Fuente sin Cable, Resistente al Calor, Sensor de Movimiento",
        note: "Gama alta: funciona sin cable con sensor de movimiento, la más versátil de coloc.",
        img: "https://m.media-amazon.com/images/I/71NrtQOKHXL._AC_UL320_.jpg",
        price: "94,99",
        rating: "4,2★",
      },
      {
        asin: "B0BG7N7PKZ",
        title: "PETKIT EVERSWEET Fuente 1,85L, Bomba Inalámbrica, Ultra Silenciosa 35dB",
        note: "Versión más compacta de PETKIT, con bomba inalámbrica y muy silenciosa.",
        img: "https://m.media-amazon.com/images/I/61n2H8LrjXL._AC_UL320_.jpg",
        price: "29,99",
        rating: "4,3★",
      },
      {
        asin: "B09SHH7TDS",
        title: "PETKIT EVERSWEET Fuente Acero Inoxidable 1,8L, Bomba Inalámbrica, Control App",
        note: "Versión en acero inoxidable de la misma gama, más fácil de mantener limpia a largo plazo.",
        img: "https://m.media-amazon.com/images/I/61e5C9JEDiL._AC_UL320_.jpg",
        price: "79,99",
        rating: "4,5★",
      },
      {
        asin: "B0F9WQGMH7",
        title: "FEELNEEDY Fuente sin Cable 3,2L, Sensor de Movimiento, Acero Inoxidable",
        note: "Funciona sin cable con sensor de movimiento, útil si no hay enchufe cerca del rincón de agua.",
        img: "https://m.media-amazon.com/images/I/71iTywZP0yL._AC_UL320_.jpg",
        price: "39,99",
        rating: "4,5★",
      },
      {
        asin: "B0FN3K2DTK",
        title: "Fuente Acero Inoxidable Estilo Grifo, Cuádruple Filtración",
        note: "Diseño tipo grifo que imita mejor el agua corriente, con filtración en cuatro etapas.",
        img: "https://m.media-amazon.com/images/I/71UJis7aDvL._AC_UL320_.jpg",
        price: "25,99",
        rating: "4,6★",
      },
    ],
  },
  {
    slug: "camas-para-perros",
    title: "Cómo elegir una cama para perro",
    dek: "Ortopédica, acolchada o de tela: qué tener en cuenta según la edad, el tamaño y el sitio donde duerme tu perro.",
    updated: "2026-09-12",
    img: "/assets/img/guias/camas-para-perros.jpg",
    intro: [
      "Un perro adulto puede pasar más de la mitad del día durmiendo o descansando, así que la cama que elijas influye tanto en su bienestar como un buen pienso. El error más común es guiarse solo por el tamaño y olvidar el tipo de soporte que necesita según la edad y las articulaciones.",
    ],
    sections: [
      {
        heading: "Espuma viscoelástica u ortopédica frente a relleno estándar",
        body: [
          "Las camas de espuma viscoelástica u ortopédica reparten el peso del cuerpo y reducen la presión en las articulaciones, especialmente importantes en perros mayores, con displasia o razas grandes propensas a problemas de cadera. El relleno estándar (fibra o similar) es más barato y ligero, adecuado para cachorros y perros jóvenes sin problemas articulares, pero se apelmaza antes con el uso diario.",
        ],
      },
      {
        heading: "Tamaño: por qué conviene pasarse antes que quedarse corto",
        body: [
          "Una cama justa impide que el perro se estire completamente al dormir, una postura habitual para liberar tensión muscular. La medida de referencia es la longitud del perro tumbado de lado con las patas estiradas, más un margen de 10-15 cm: si dudas entre dos tallas, la más grande casi siempre es la mejor elección.",
        ],
      },
      {
        heading: "Funda lavable y resistencia a mordiscos",
        body: [
          "Una funda extraíble y lavable a máquina es prácticamente obligatoria: la cama acumula pelo, babas y suciedad del suelo, y lavar solo la funda alarga mucho la vida del relleno interior. Si tu perro tiene tendencia a morder o escarbar la cama, busca materiales reforzados o cosidos dobles en los bordes, el punto por donde suelen empezar a romperse.",
        ],
      },
      {
        heading: "Dónde va a estar la cama",
        body: [
          "Una cama para interior no necesita ser impermeable, pero una que vaya a estar cerca de una puerta a terraza o jardín sí agradece una base resistente a la humedad. Si el perro duerme en un suelo frío (baldosa, terrazo), una base elevada o con más grosor de espuma aísla mejor que una colchoneta fina directamente en el suelo.",
        ],
      },
    ],
    checklist: [
      "Espuma ortopédica si el perro es mayor, grande o tiene problemas articulares",
      "Talla con margen: mejor pasarse que quedarse corto",
      "Funda extraíble y lavable a máquina",
      "Refuerzos en los bordes si el perro muerde o escarba",
      "Aislamiento del frío si el suelo es de baldosa o terrazo",
    ],
    faq: [
      {
        q: "¿Necesito una cama ortopédica si mi perro es joven y sano?",
        a: "No es imprescindible: una cama de relleno estándar de calidad es suficiente para un perro joven sin problemas articulares. La ortopédica se recomienda sobre todo en perros mayores, razas grandes con predisposición a displasia, o cualquier perro con un diagnóstico articular del veterinario.",
      },
      {
        q: "¿Qué talla elijo si mi perro está entre dos tamaños?",
        a: "Elige siempre la talla más grande de las dos: una cama algo más grande de lo estrictamente necesario no incomoda, pero una cama justa impide que el perro se estire del todo al dormir.",
      },
    ],
    products: [
      {
        asin: "B0FDPHSDQ4",
        title: "Feandrea Cama Antideslizante 71x55x18cm, Funda Extraíble",
        note: "Entrada de gama para perros pequeños, base antideslizante y funda lavable.",
        img: "https://m.media-amazon.com/images/I/81hH2SG60HL._AC_UL320_.jpg",
        price: "15,99",
        rating: "4,4★",
      },
      {
        asin: "B0GNL361J3",
        title: "YAGU Cama para Perros y Gatos T-1, 50x38x18cm, hasta 3kg",
        note: "Talla pequeña específica para cachorros y razas mini hasta 3 kg.",
        img: "https://m.media-amazon.com/images/I/814MnhWyptL._AC_UL320_.jpg",
        price: "31,25",
        rating: "4,7★",
      },
      {
        asin: "B0CHDLZ1P7",
        title: "FURTIME Cama Grande Lavable 89x63x23cm, Anti-Ansiedad con Soporte",
        note: "Bordes elevados tipo donut, pensada para perros que buscan sensación de refugio.",
        img: "https://m.media-amazon.com/images/I/81KshJZ9nBL._AC_UL320_.jpg",
        price: "31,99",
        rating: "4,4★",
      },
      {
        asin: "B0GK7YNX6P",
        title: "Feandrea Cama Ortopédica Grande Lavable, 104x69x17cm, Franela",
        note: "Espuma ortopédica de nivel medio, buen punto de partida para perros mayores.",
        img: "https://m.media-amazon.com/images/I/71Wky2tS9FL._AC_UL320_.jpg",
        price: "47,99",
        rating: "4,4★",
      },
      {
        asin: "B0DCJKCTT7",
        title: "WAVVE Cama Extra Grande Ortopédica 112x81x7,6cm, Impermeable Lavable",
        note: "Base impermeable, práctica para perros que duermen cerca de la puerta al jardín.",
        img: "https://m.media-amazon.com/images/I/61Jb9KeuX7L._AC_UL320_.jpg",
        price: "37,99",
        rating: "4,7★",
      },
      {
        asin: "B0BNLWVPHD",
        title: "EHEYCIGA Cama Extra Grande 112x81x16cm, Espuma Viscoelástica",
        note: "Espuma viscoelástica de mayor grosor, orientada a razas grandes con más peso.",
        img: "https://m.media-amazon.com/images/I/61E5+Tg-R9L._AC_UL320_.jpg",
        price: "49,99",
        rating: "4,6★",
      },
      {
        asin: "B06XQ492N8",
        title: "JOYELF Cama Grande de Espuma Viscoelástica, Sofá Ortopédico con Funda",
        note: "Gama alta con funda de mayor calidad y acabado tipo sofá para el salón.",
        img: "https://m.media-amazon.com/images/I/61cCGmQ2-pL._AC_UL320_.jpg",
        price: "89,99",
        rating: "4,6★",
      },
      {
        asin: "B0BJK9YF5N",
        title: "Feandrea Cama Ortopédica Sofá, 122x85x20cm",
        note: "Versión más grande de la gama ortopédica Feandrea, pensada para razas grandes.",
        img: "https://m.media-amazon.com/images/I/71HE0lKpeoL._AC_UL320_.jpg",
        price: "40,79",
        rating: "4,5★",
      },
      {
        asin: "B08NC88YD7",
        title: "Bedsure Sofá Cama Ortopédica Lavable, 89x63cm",
        note: "Marca de referencia en camas ortopédicas, acabado tipo sofá con funda extraíble.",
        img: "https://m.media-amazon.com/images/I/714QScIqOfL._AC_UL320_.jpg",
        price: "42,49",
        rating: "4,6★",
      },
      {
        asin: "B0D2KR5Y8F",
        title: "COZY KISS Cama Ortopédica XL, 107x76x19cm",
        note: "Talla XL con espuma ortopédica, pensada para razas grandes con más peso.",
        img: "https://m.media-amazon.com/images/I/71divvY6-0L._AC_UL320_.jpg",
        price: "42,99",
        rating: "4,6★",
      },
      {
        asin: "B0H5BTX84X",
        title: "EDAGNY Cama Redonda Calmante para Perro Pequeño",
        note: "Formato donut de borde alto, pensado para perros que buscan sensación de refugio al dormir.",
        img: "https://m.media-amazon.com/images/I/81ZlYVUjV8L._AC_UL320_.jpg",
        price: "39,99",
        rating: "4,6★",
      },
    ],
  },
  {
    slug: "transportines-para-mascotas",
    title: "Transportines para perros y gatos: cómo elegir el adecuado",
    dek: "Rígido, blando o mochila: qué transportín necesitas según el medio de transporte y el tamaño de tu mascota.",
    updated: "2026-09-11",
    img: "/assets/img/guias/transportines-para-mascotas.jpg",
    intro: [
      "Un transportín no es solo para el veterinario: viajar en coche, tren o avión con normas de seguridad exige un tipo concreto, y no todos los modelos sirven para todos los medios de transporte. Elegir mal significa descubrirlo el día del viaje, cuando ya no hay margen para cambiarlo.",
    ],
    sections: [
      {
        heading: "Rígido, blando o mochila",
        body: [
          "Los transportines rígidos (de plástico, con rejilla de ventilación) son los más seguros para viajes largos en coche y los que exigen la mayoría de aerolíneas para bodega, porque protegen mejor ante golpes. Los transportines blandos (bolsa acolchada) son más ligeros y cómodos para trayectos cortos o para llevar bajo el asiento delantero de un avión, pero ofrecen menos protección estructural.",
          "Las mochilas de transporte están pensadas sobre todo para gatos pequeños o perros muy pequeños en trayectos a pie o en transporte público, priorizando la comodidad de quien lo lleva sobre el espacio interior de la mascota.",
        ],
      },
      {
        heading: "Tamaño: que pueda girar, tumbarse y ponerse de pie",
        body: [
          "La regla general es que la mascota debe poder entrar, girarse por completo, tumbarse estirada y ponerse de pie sin agachar la cabeza. Un transportín pequeño no es más seguro por ser ajustado: es simplemente incómodo y puede generar más estrés durante el viaje.",
        ],
      },
      {
        heading: "Requisitos si vas a viajar en avión",
        body: [
          "Cada aerolínea tiene sus propias medidas máximas y requisitos de ventilación, tanto para cabina como para bodega, así que hay que comprobar la normativa concreta de la compañía antes de comprar, no solo que el transportín diga \"apto para avión\" de forma genérica. Para cabina casi siempre se exige que quepa bajo el asiento delantero, lo que limita bastante el tamaño frente a un transportín de coche.",
        ],
      },
      {
        heading: "Ventilación, sujeción y limpieza",
        body: [
          "La ventilación en varios lados (no solo delante) evita que se acumule calor en trayectos largos o en días de calor. Para el coche, comprobar que el transportín se puede fijar con el cinturón de seguridad reduce el riesgo en frenazos bruscos. Una base o cojín extraíble y lavable facilita mucho la limpieza después de un viaje largo o si la mascota se marea.",
        ],
      },
    ],
    checklist: [
      "Rígido para viajes largos en coche o bodega de avión; blando o mochila para trayectos cortos",
      "Tamaño que permita girar, tumbarse y ponerse de pie sin tocar el techo",
      "Comprobar la normativa concreta de la aerolínea si vas a volar",
      "Ventilación en varios lados, no solo en la puerta frontal",
      "Posibilidad de fijarlo con el cinturón de seguridad en el coche",
    ],
    faq: [
      {
        q: "¿Qué transportín necesito para viajar en avión?",
        a: "Depende de si va en cabina o en bodega: en cabina casi siempre debe caber bajo el asiento delantero (normalmente blando o semirrígido), y en bodega la mayoría de aerolíneas exige uno rígido con ventilación en varios lados. Revisa siempre las medidas exactas de la compañía concreta antes de comprar.",
      },
      {
        q: "¿El transportín tiene que ser exactamente del tamaño de mi mascota?",
        a: "No exactamente: tiene que ser lo bastante grande para que pueda girarse, tumbarse estirada y ponerse de pie sin agachar la cabeza. Ni tan grande que se mueva descontroladamente dentro durante el trayecto, ni tan justo que le resulte incómodo.",
      },
    ],
    products: [
      {
        asin: "B0C6DYGMR2",
        title: "lionto Transportín Rígido Polipropileno 15kg, 48x31,5x33cm",
        note: "Entrada de gama en formato rígido, buena opción para trayectos cortos en coche.",
        img: "https://m.media-amazon.com/images/I/61juALRAcGL._AC_UL320_.jpg",
        price: "18,95",
        rating: "4,2★",
      },
      {
        asin: "B0FC1GS517",
        title: "Transportín Plegable y Transpirable con Correa al Hombro, 45x28x28cm",
        note: "Formato blando plegable, cómodo para guardar cuando no se usa.",
        img: "https://m.media-amazon.com/images/I/813Vk9ya4OL._AC_UL320_.jpg",
        price: "20,99",
        rating: "4,5★",
      },
      {
        asin: "B07MGH27ZS",
        title: "morpilot Transportín Blando Transpirable con Correa de Hombro",
        note: "Malla transpirable en varios lados, adecuado para trayectos cortos en transporte público.",
        img: "https://m.media-amazon.com/images/I/81-gGkHnEML._AC_UL320_.jpg",
        price: "34,99",
        rating: "4,6★",
      },
      {
        asin: "B00V5624HA",
        title: "PawHut Transportín 2 en 1 Mochila o Carrito de Viaje con Ruedas",
        note: "Combina mochila y carrito con ruedas, útil para desplazamientos largos a pie.",
        img: "https://m.media-amazon.com/images/I/61yEePPkWfL._AC_UL320_.jpg",
        price: "35,14",
        rating: "4,4★",
      },
      {
        asin: "B00OP6SMCI",
        title: "Amazon Basics Transportín Rígido 2 Puertas con Carga Superior, 48cm",
        note: "Rígido con dos puertas de acceso, buen equilibrio precio-seguridad para el coche.",
        img: "https://m.media-amazon.com/images/I/71WgHnZShvL._AC_UL320_.jpg",
        price: "41,79",
        rating: "4,6★",
      },
      {
        asin: "B0H8N3F8TG",
        title: "VOBUKE Transportín Expandible 200%, Aprobado por Aerolíneas, hasta 10kg",
        note: "Diseñado según requisitos habituales de cabina; revisa siempre tu aerolínea concreta.",
        img: "https://m.media-amazon.com/images/I/81b2X-j5fwL._AC_UL320_.jpg",
        price: "49,99",
        rating: "5,0★",
      },
      {
        asin: "B08BZ7C26G",
        title: "Pecute Mochila Transportín para Gato, Expandible y Plegable, hasta 6kg",
        note: "Gama alta en formato mochila, con panel expandible para más espacio en parada.",
        img: "https://m.media-amazon.com/images/I/91duHD8zX5L._AC_UL320_.jpg",
        price: "59,99",
        rating: "4,8★",
      },
      {
        asin: "B0F387675S",
        title: "Kerbl Pet Caja de Transporte Expedion, 45x30x30cm",
        note: "Rígido de plástico y precio ajustado, buena opción de entrada para perros y gatos pequeños.",
        img: "https://m.media-amazon.com/images/I/71Se3wM4LqL._AC_UL320_.jpg",
        price: "21,24",
        rating: "4,0★",
      },
      {
        asin: "B0797D5RNZ",
        title: "Ferplast Transportín Gato, Techo Abrible, con Cojín y Comedero, hasta 8kg",
        note: "Rígido de una marca especializada en transportines, con techo abrible para sacar a la mascota con calma.",
        img: "https://m.media-amazon.com/images/I/71c0L6Rf1oL._AC_UL320_.jpg",
        price: "66,30",
        rating: "4,1★",
      },
      {
        asin: "B0D5CCMQKG",
        title: "Petsfit Transportín Aéreo con Almohada, Material Premium",
        note: "Formato blando de gama alta, pensado específicamente para viajar en cabina de avión.",
        img: "https://m.media-amazon.com/images/I/81guz1dmFRL._AC_UL320_.jpg",
        price: "55,56",
        rating: "4,6★",
      },
      {
        asin: "B0G6693GPP",
        title: "Larkson Transportín hasta 12kg, Cumple Estándares para Avión",
        note: "Gama alta en formato blando, revisado según los requisitos habituales de aerolíneas.",
        img: "https://m.media-amazon.com/images/I/71upyw5l+fL._AC_UL320_.jpg",
        price: "79,95",
        rating: "4,4★",
      },
    ],
  },
  {
    slug: "areneros-autolimpiables-para-gatos",
    title: "Areneros autolimpiables para gatos: qué mirar antes de comprar",
    dek: "Capacidad, sensores de seguridad y control por app: si un arenero autolimpiable compensa el precio en tu caso.",
    updated: "2026-09-10",
    img: "/assets/img/guias/areneros-autolimpiables-para-gatos.jpg",
    intro: [
      "Un arenero autolimpiable puede ahorrar la tarea diaria de recoger arena, pero es una de las compras más caras de esta lista y no siempre compensa: depende del número de gatos, del tipo de arena que usan y de cuánto valores automatizar esa tarea.",
    ],
    sections: [
      {
        heading: "Cómo funcionan y qué tipo de arena necesitan",
        body: [
          "La mayoría de areneros autolimpiables usan un rastrillo o un tambor giratorio que separa los grumos de arena limpia después de cada uso, y los deposita en un compartimento cerrado. Casi todos requieren arena aglomerante de grano fino específica: usar una arena no compatible puede atascar el mecanismo o hacer que no separe bien los residuos, así que conviene comprobarlo antes de la primera compra de arena.",
        ],
      },
      {
        heading: "Sensores de seguridad y peso mínimo del gato",
        body: [
          "Los sensores de peso y de movimiento evitan que el mecanismo se active mientras el gato sigue dentro, una función de seguridad imprescindible, no un extra opcional. Revisa el peso mínimo que detecta el sensor: algunos modelos no reconocen bien a gatitos muy pequeños y pueden no activarse o, peor, no detectarlos como \"dentro\" del arenero.",
        ],
      },
      {
        heading: "Capacidad para varios gatos",
        body: [
          "Un arenero autolimpiable individual puede quedarse corto con dos o más gatos que usan la misma unidad varias veces al día: revisa la capacidad del cajón de residuos y cada cuánto pide vaciarse. La recomendación general de una bandeja por gato más una extra se mantiene también con los autolimpiables, aunque el mantenimiento diario sea menor.",
        ],
      },
      {
        heading: "Ruido, control por app y mantenimiento",
        body: [
          "El ciclo de limpieza automático hace ruido de motor y de arena moviéndose, lo que puede asustar a gatos sensibles al principio: un periodo de adaptación con el arenero apagado ayuda a que se acostumbren. El control por app permite ver el historial de usos (útil para detectar cambios de hábito que a veces son la primera señal de un problema de salud), pero no sustituye la limpieza manual del cajón de residuos y el cambio completo de arena cada cierto tiempo.",
        ],
      },
    ],
    checklist: [
      "Comprobar el tipo de arena compatible antes de comprar",
      "Sensores de peso y movimiento como función imprescindible, no opcional",
      "Capacidad suficiente para el número de gatos de casa",
      "Periodo de adaptación para gatos sensibles al ruido del motor",
      "Mantenimiento manual periódico aunque el modelo sea autolimpiable",
    ],
    faq: [
      {
        q: "¿Compensa un arenero autolimpiable para un solo gato?",
        a: "Depende de cuánto valores no tener que recoger arena a diario: para un solo gato, un arenero manual bien mantenido cumple perfectamente y cuesta una fracción del precio. El autolimpiable aporta más valor con varios gatos o si por horarios no puedes limpiar la bandeja todos los días.",
      },
      {
        q: "¿Es seguro para gatitos o gatos mayores?",
        a: "Depende del modelo y de su peso mínimo detectable: algunos autolimpiables no están recomendados para gatitos muy pequeños o gatos con movilidad reducida, porque el sensor puede no reconocerlos bien. Revisa siempre las especificaciones de peso mínimo y máximo antes de comprarlo si tienes un gatito o un gato mayor.",
      },
    ],
    products: [
      {
        asin: "B0H9XZ8PY9",
        title: "Nobleza Arenero Autolimpiable Abierto, Multi-Sensores de Seguridad",
        note: "Entrada de gama en formato abierto, más económico que los modelos cerrados.",
        img: "https://m.media-amazon.com/images/I/61-6frH-dyL._AC_UL320_.jpg",
        price: "169,99",
        rating: "3,4★",
      },
      {
        asin: "B0G3XV7ZKY",
        title: "Ellenpent Arenero Autolimpiable Abierto, Sin Olores, Capacidad Grande",
        note: "Cajón de residuos de capacidad amplia, pensado para reducir vaciados frecuentes.",
        img: "https://m.media-amazon.com/images/I/71WlNgp6pML._AC_UL320_.jpg",
        price: "197,60",
        rating: "4,2★",
      },
      {
        asin: "B0HDP9NRV2",
        title: "FEELNEEDY Arenero Autolimpiable 65L, Control de Olores, App en Tiempo Real",
        note: "Control de olores más agresivo y monitorización de uso por app.",
        img: "https://m.media-amazon.com/images/I/715nOZbq21L._AC_UL320_.jpg",
        price: "194,76",
        rating: "4,4★",
      },
      {
        asin: "B0H6LK3LR8",
        title: "Redkey X1 Arenero Autolimpiable 95L, Eliminación de Olores, Control App",
        note: "Depósito de gran tamaño (95L), pensado para hogares con dos o más gatos.",
        img: "https://m.media-amazon.com/images/I/61qXzsjlSUL._AC_UL320_.jpg",
        price: "234,99",
        rating: "4,0★",
      },
      {
        asin: "B0FLPKZ4RS",
        title: "Devoko Arenero Autolimpiable Grande 90L, Gran Capacidad",
        note: "Similar en capacidad al anterior, buena alternativa a comparar en precio.",
        img: "https://m.media-amazon.com/images/I/71uYgOSxg5L._AC_UL320_.jpg",
        price: "299,99",
        rating: "4,3★",
      },
      {
        asin: "B0D9QGW2M6",
        title: "PETKIT Pura MAX 2 Arenero Autolimpiable, Anti-Fugas, Control App",
        note: "Uno de los modelos más valorados en volumen de opiniones de la categoría.",
        img: "https://m.media-amazon.com/images/I/61LSN9Hwj4L._AC_UL320_.jpg",
        price: "409,99",
        rating: "4,4★",
      },
      {
        asin: "B0FJFB6YXB",
        title: "PETKIT PUROBOT MAX Pro 2 Arenero Autolimpiable, Cámara AI, Entrada Mayor",
        note: "Gama alta: cámara con reconocimiento de gato y entrada más amplia.",
        img: "https://m.media-amazon.com/images/I/61yeCBDa2mL._AC_UL320_.jpg",
        price: "589,99",
        rating: "4,2★",
      },
      {
        asin: "B009B83V76",
        title: "Catit Smartsift, Bandeja Sanitaria Automática",
        note: "La opción más económica de la categoría, con rastrillo giratorio de una marca especializada en accesorios para gatos.",
        img: "https://m.media-amazon.com/images/I/61p7nlT1hRL._AC_UL320_.jpg",
        price: "96,36",
        rating: "3,7★",
      },
      {
        asin: "B0GTYCSCWT",
        title: "CATLINK Arenero Autolimpiable, Entrada Superior, WiFi 5GHz, 12L",
        note: "Marca alternativa a PETKIT, con entrada superior para gatos que prefieren saltar dentro.",
        img: "https://m.media-amazon.com/images/I/71AzNKoI58L._AC_UL320_.jpg",
        price: "249,99",
        rating: "4,1★",
      },
      {
        asin: "B0GD6NHKVK",
        title: "oneisall Arenero Autolimpiable XXL para Gatos Grandes",
        note: "Pensado específicamente para gatos grandes, con rejilla de acero inoxidable.",
        img: "https://m.media-amazon.com/images/I/71y+nJpOuJL._AC_UL320_.jpg",
        price: "170,99",
        rating: "3,9★",
      },
      {
        asin: "B0H35LPVDG",
        title: "PETKIT PUROBOT MAX 3 Arenero Autolimpiable, Entrada Mayor, Eliminación Múltiple de Olores",
        note: "Gama alta de PETKIT con entrada más amplia y mejor control de olores que los modelos anteriores.",
        img: "https://m.media-amazon.com/images/I/71U95CNT9VL._AC_UL320_.jpg",
        price: "519,99",
        rating: "4,8★",
      },
    ],
  },
  {
    slug: "rascadores-para-gatos",
    title: "Cómo elegir un rascador o árbol para gatos",
    dek: "Postes, plataformas y altura: qué necesita tu gato para no acabar rascando el sofá.",
    updated: "2026-09-09",
    img: "/assets/img/guias/rascadores-para-gatos.jpg",
    intro: [
      "Rascar es una necesidad física del gato (marcar territorio y mantener las uñas), no un capricho: si no tiene un rascador que le convenza, el sofá o la esquina de un mueble hará ese papel. La clave está en la altura, la estabilidad y el material del poste, no solo en el tamaño del mueble.",
    ],
    sections: [
      {
        heading: "Altura y estabilidad, lo que más importa",
        body: [
          "Un rascador debe permitir que el gato se estire completamente en vertical, con las patas delanteras extendidas al máximo: si es demasiado bajo, el gato no lo usará igual de bien y puede recurrir a un sofá o cortina donde sí puede estirarse. La base tiene que ser ancha y pesada en relación con la altura del mueble: un árbol alto con base estrecha se tambalea al primer salto, y un gato que se ha llevado un susto no vuelve a usarlo con confianza.",
        ],
      },
      {
        heading: "Material del poste: sisal frente a alfombra o cartón",
        body: [
          "La cuerda de sisal es el material más recomendado por veterinarios y etólogos: tiene una textura que satisface el instinto de rascado y aguanta mejor el desgaste que otros materiales. Los postes forrados en moqueta o alfombra son más baratos pero se deshilachan antes, y para colmo tienen una textura parecida a la de una alfombra de casa, lo que puede confundir al gato sobre dónde está permitido rascar.",
        ],
      },
      {
        heading: "Torre multinivel frente a poste simple",
        body: [
          "Una torre con varias plataformas añade zonas de descanso en altura, algo que los gatos buscan de forma natural para vigilar su territorio, y resulta especialmente útil en pisos pequeños donde no hay muebles altos accesibles. Un poste rascador simple cubre la necesidad de rascar pero no aporta ese espacio vertical de descanso, así que la elección depende de si el objetivo es solo el rascado o también dar al gato una zona propia elevada.",
        ],
      },
      {
        heading: "Ubicación dentro de casa",
        body: [
          "Colocar el rascador cerca de donde el gato ya duerme o pasa tiempo (no escondido en una habitación poco usada) aumenta mucho las probabilidades de que lo adopte como suyo desde el primer día. Si el gato ya tiene un mueble favorito para arañar, poner el rascador nuevo justo al lado facilita la transición antes de moverlo poco a poco a su ubicación definitiva.",
        ],
      },
    ],
    checklist: [
      "Altura suficiente para que el gato se estire por completo en vertical",
      "Base ancha y pesada en proporción a la altura de la torre",
      "Postes de sisal en lugar de moqueta o alfombra",
      "Torre multinivel si buscas también zona de descanso en altura",
      "Ubicación inicial cerca de donde el gato ya pasa tiempo",
    ],
    faq: [
      {
        q: "¿Por qué mi gato sigue rascando el sofá si tiene rascador?",
        a: "Casi siempre es un problema de ubicación, altura o material, no de que el gato \"no quiera\" usarlo: revisa si el rascador está en una zona que el gato frecuenta, si le permite estirarse del todo y si el poste es de sisal. Cambiar uno de esos tres factores suele resolver el problema en pocos días.",
      },
      {
        q: "¿Necesito una torre grande si tengo poco espacio?",
        a: "No necesariamente: hay torres compactas de base ancha y altura media que cubren la necesidad de rascado y un mínimo de zona elevada sin ocupar mucho suelo. Lo importante es la estabilidad de la base, no el tamaño total del mueble.",
      },
    ],
    products: [
      {
        asin: "B09NLS54TR",
        title: "Feandrea Torre para Gatos, Colección Clawfy, Gris Paloma",
        note: "Entrada de gama compacta, buena opción para pisos con poco espacio.",
        img: "https://m.media-amazon.com/images/I/61q37Ejyf5L._AC_UL320_.jpg",
        price: "26,99",
        rating: "4,6★",
      },
      {
        asin: "B08MQDTYFV",
        title: "Feandrea Torre para Gatos 115cm, Postes de Sisal",
        note: "Altura media con varios postes de sisal y una plataforma de descanso.",
        img: "https://m.media-amazon.com/images/I/81Rbzo6GPqL._AC_UL320_.jpg",
        price: "32,29",
        rating: "4,6★",
      },
      {
        asin: "B06X6J3L65",
        title: "Amazon Basics Torre Multinivel para Gatos, 117cm de Altura",
        note: "Buena relación calidad-precio en formato multinivel de tamaño medio.",
        img: "https://m.media-amazon.com/images/I/91OEO3v2EiL._AC_UL320_.jpg",
        price: "31,45",
        rating: "4,7★",
      },
      {
        asin: "B08WS1MW6Y",
        title: "Mobiclinic Árbol Rascador 3 Alturas, Refugio y Postes de Sisal",
        note: "Incluye refugio cerrado además de plataformas, útil para gatos más tímidos.",
        img: "https://m.media-amazon.com/images/I/51YnkNnTCJL._AC_UL320_.jpg",
        price: "29,95",
        rating: "4,4★",
      },
      {
        asin: "B0BN9YL1KH",
        title: "HOMIDEC Árbol Rascador 145cm, 7 Postes, Varios Niveles",
        note: "Más alto y con más postes de sisal, pensado para dos gatos o gatos muy activos.",
        img: "https://m.media-amazon.com/images/I/71AvbGKoyoL._AC_UL320_.jpg",
        price: "42,99",
        rating: "4,6★",
      },
      {
        asin: "B07YRKTF9Y",
        title: "Yaheetech Árbol Rascador 139cm, Postes de Sisal, Estable a los Saltos",
        note: "Base reforzada pensada específicamente para mejorar la estabilidad al saltar.",
        img: "https://m.media-amazon.com/images/I/81esLlocZuL._AC_UL320_.jpg",
        price: "44,99",
        rating: "4,6★",
      },
      {
        asin: "B0FPWSKBGG",
        title: "FUKUMARU Torre de 4 Niveles hasta el Techo (251-274cm)",
        note: "Gama alta: modelo de suelo a techo para maximizar el espacio vertical.",
        img: "https://m.media-amazon.com/images/I/51YxtmgG-VL._AC_UL320_.jpg",
        price: "75,99",
        rating: "4,6★",
      },
      {
        asin: "B0DRY5G74Y",
        title: "Amazon Basics Árbol para Gatos de Interior, Varios Niveles, con Hamaca",
        note: "Buena relación calidad-precio de marca propia de Amazon, con hamaca incluida.",
        img: "https://m.media-amazon.com/images/I/71xHUzPGutL._AC_UL320_.jpg",
        price: "56,69",
        rating: "4,7★",
      },
      {
        asin: "B0GFMYJ85G",
        title: "Gitelsnour Árbol Rascador para Gatitos, 107cm",
        note: "Altura más compacta, buena opción de entrada para pisos pequeños o gatitos jóvenes.",
        img: "https://m.media-amazon.com/images/I/81DyaoMA2DL._AC_UL320_.jpg",
        price: "32,48",
        rating: "4,8★",
      },
      {
        asin: "B0GT7XJZ45",
        title: "Heybly Árbol para Gatos 173cm",
        note: "Altura considerable con acabado cuidado, alternativa de gama alta a los árboles más básicos.",
        img: "https://m.media-amazon.com/images/I/81pjkYMRsKL._AC_UL320_.jpg",
        price: "82,99",
        rating: "4,6★",
      },
      {
        asin: "B0DF17N1BS",
        title: "PawHut Árbol Rascador Torre Escalador, 2 Cuevas, 173cm",
        note: "Incluye dos cuevas cerradas, útil en casas con más de un gato o gatos más tímidos.",
        img: "https://m.media-amazon.com/images/I/71WlPyDDAsL._AC_UL320_.jpg",
        price: "56,99",
        rating: "4,5★",
      },
    ],
  },
  {
    slug: "juguetes-interactivos-para-perros",
    title: "Juguetes interactivos para perros: cómo elegir sin acertar a ciegas",
    dek: "Dispensadores de comida, puzzles de olfato y juguetes de rellenar: qué tipo cansa mentalmente a tu perro de verdad.",
    updated: "2026-09-08",
    img: "/assets/img/guias/juguetes-interactivos-para-perros.jpg",
    intro: [
      "El cansancio mental agota tanto o más que el físico, y un perro que se aburre en casa es un perro con más probabilidades de desarrollar conductas destructivas. Los juguetes interactivos cubren esa necesidad, pero el tipo correcto depende del nivel de dificultad que tu perro ya domine, no de cuál parece más vistoso en la caja.",
    ],
    sections: [
      {
        heading: "Rellenables frente a puzzles de niveles",
        body: [
          "Los juguetes rellenables (tipo Kong) esconden comida o pasta de premios dentro de un cuerpo de goma resistente: el perro tiene que morder y manipular para conseguir el premio, y sirven tanto para entretenimiento como para masticadores compulsivos. Los puzzles de niveles (con piezas deslizantes o giratorias que esconden premios) trabajan más la resolución de problemas que la masticación, y muchos permiten subir de dificultad a medida que el perro aprende el mecanismo.",
        ],
      },
      {
        heading: "Alfombras y mantas de olfato",
        body: [
          "Las alfombras de olfato (snuffle mats) esconden premios entre tiras de tela que el perro tiene que rebuscar con el hocico, un ejercicio que trabaja el olfato en lugar de la vista o la lógica. Son especialmente útiles para perros ansiosos durante la comida o que comen demasiado rápido, porque ralentizan mucho la ingesta sin necesidad de comederos especiales.",
        ],
      },
      {
        heading: "Nivel de dificultad y supervisión",
        body: [
          "Empezar con un nivel de dificultad demasiado alto frustra al perro y puede hacer que pierda interés en el juguete entero, no solo en ese ejercicio. La mayoría de puzzles indican un nivel (principiante, intermedio, avanzado): conviene empezar por el más bajo aunque el perro parezca listo, y subir de nivel según lo resuelva con soltura.",
          "Los juguetes con piezas pequeñas desmontables (tapones, discos) requieren supervisión en perros que tienden a masticar y tragar piezas, sobre todo al principio hasta comprobar cómo se relaciona el perro con ese juguete en concreto.",
        ],
      },
      {
        heading: "Material y resistencia",
        body: [
          "El caucho natural resistente a mordiscos aguanta mejor que el plástico duro en perros con mandíbula fuerte, y es más seguro si el perro tiende a masticar el propio juguete además de buscar el premio. Revisa que el juguete esté clasificado para el tamaño y la fuerza de mordida de tu perro: un juguete pensado para razas pequeñas no dura nada con un perro grande y mordedor.",
        ],
      },
    ],
    checklist: [
      "Rellenable para masticadores; puzzle de niveles para trabajar resolución de problemas",
      "Alfombra de olfato si el perro come muy rápido o se aburre en casa",
      "Empezar siempre por el nivel de dificultad más bajo",
      "Supervisión en juguetes con piezas pequeñas desmontables",
      "Material y resistencia acordes a la fuerza de mordida del perro",
    ],
    faq: [
      {
        q: "¿Qué juguete interactivo elijo si mi perro es un masticador fuerte?",
        a: "Los juguetes rellenables de caucho natural resistente son la opción más segura, porque están pensados para aguantar mordiscos intensos mientras el perro trabaja para sacar el premio de dentro. Evita puzzles con piezas de plástico fino si tu perro tiende a morder el juguete entero, no solo a manipularlo.",
      },
      {
        q: "¿Con qué frecuencia debo usar juguetes interactivos?",
        a: "No hay una cifra única, pero incorporarlos varias veces por semana (por ejemplo, sustituyendo el comedero normal en alguna comida) ya aporta un cansancio mental notable. Ir subiendo la dificultad progresivamente evita que el perro pierda interés por aburrimiento o frustración.",
      },
    ],
    products: [
      {
        asin: "B003TOKTEG",
        title: "TRIXIE Dog Activity Turn Around, Juego Estratégico 22x33cm",
        note: "Entrada de gama y buen primer puzzle para perros que no han usado ninguno.",
        img: "https://m.media-amazon.com/images/I/61hqbaRp-PL._AC_UL320_.jpg",
        price: "8,19",
        rating: "4,2★",
      },
      {
        asin: "B0DY1QDTGZ",
        title: "QGGTQG Puzzle Dispensador de Comida para Perros",
        note: "Dispensador básico de nivel inicial, fácil de limpiar entre usos.",
        img: "https://m.media-amazon.com/images/I/71d2VTYl9HL._AC_UL320_.jpg",
        price: "12,99",
        rating: "4,2★",
      },
      {
        asin: "B0DL4CJR7L",
        title: "Romicotas Puzzle de Olfato con 3 Niveles de Dificultad",
        note: "Permite subir de nivel a medida que el perro aprende el mecanismo.",
        img: "https://m.media-amazon.com/images/I/61FAndc61JL._AC_UL320_.jpg",
        price: "12,84",
        rating: "4,3★",
      },
      {
        asin: "B0B6N5L1P9",
        title: "Nobleza Alfombra Olfativa (Snuffle Mat), Juego de Inteligencia",
        note: "Buena opción para perros que comen demasiado rápido o se aburren en casa.",
        img: "https://m.media-amazon.com/images/I/61zgOfqMRUL._AC_UL320_.jpg",
        price: "16,99",
        rating: "4,4★",
      },
      {
        asin: "B009WPTW9E",
        title: "TRIXIE Dog Activity Poker Box 2, Juego Interactivo 31x31cm",
        note: "Nivel intermedio con varios compartimentos, buen siguiente paso tras el Turn Around.",
        img: "https://m.media-amazon.com/images/I/61hOH6bN8pL._AC_UL320_.jpg",
        price: "24,50",
        rating: "4,3★",
      },
      {
        asin: "B0BB214KF9",
        title: "Dufuso Rompecabezas de Alimentación Lenta, 2 Niveles de Dificultad",
        note: "Combina alimentación lenta con reto mental en un solo juguete.",
        img: "https://m.media-amazon.com/images/I/71s5ja0qNhL._AC_UL320_.jpg",
        price: "27,99",
        rating: "4,2★",
      },
      {
        asin: "B087DNTV2V",
        title: "Outward Hound Nina Ottosson MultiPuzzle, Módulos Deslizantes",
        note: "Gama alta de una de las marcas de referencia en puzzles caninos.",
        img: "https://m.media-amazon.com/images/I/71RVzutRrUS._AC_UL320_.jpg",
        price: "30,99",
        rating: "4,2★",
      },
      {
        asin: "B0002AR15U",
        title: "KONG Classic Juguete Rellenable, Talla Pequeña",
        note: "El rellenable de referencia que se menciona en cualquier guía de juguetes caninos; caucho resistente.",
        img: "https://m.media-amazon.com/images/I/61CT7VZTqQL._AC_UL320_.jpg",
        price: "8,79",
        rating: "4,5★",
      },
      {
        asin: "B003ALMW0M",
        title: "KONG Wobbler Dispensador de Comida, Talla Mediana/Grande",
        note: "Dispensador que se tambalea al moverlo, obliga al perro a trabajar para sacar cada premio.",
        img: "https://m.media-amazon.com/images/I/61rszHw5N5L._AC_UL320_.jpg",
        price: "24,48",
        rating: "4,4★",
      },
      {
        asin: "B0024E4YXO",
        title: "KONG Goodie Bone, Hueso Dispensador de Golosinas en Caucho Resistente",
        note: "Formato hueso en el mismo caucho resistente de KONG, alternativa de forma al Classic.",
        img: "https://m.media-amazon.com/images/I/61kQMNAchPL._AC_UL320_.jpg",
        price: "17,99",
        rating: "4,4★",
      },
      {
        asin: "B0B9S12KHZ",
        title: "JOPHEK Dispensador de Premios Interactivo",
        note: "Puzzle económico de nivel inicial, válido también para perros pequeños, gatos y cachorros.",
        img: "https://m.media-amazon.com/images/I/61bjS7QElNL._AC_UL320_.jpg",
        price: "13,99",
        rating: "4,5★",
      },
    ],
  },
  {
    slug: "collares-gps-para-mascotas",
    title: "Collares GPS para perros y gatos: qué mirar antes de comprar",
    dek: "Cobertura, autonomía de batería y suscripción: cómo elegir un localizador que funcione cuando de verdad lo necesitas.",
    updated: "2026-09-07",
    img: "/assets/img/guias/collares-gps-para-mascotas.jpg",
    intro: [
      "Un collar GPS solo sirve si funciona en el peor momento posible: cuando la mascota ya se ha escapado. Antes de comprar conviene mirar más allá del precio inicial, porque la cobertura real y el coste de mantenimiento varían mucho entre modelos.",
    ],
    sections: [
      {
        heading: "Con suscripción frente a sin suscripción",
        body: [
          "Los localizadores con tarjeta SIM y suscripción mensual usan la red de datos móviles para dar ubicación en tiempo real prácticamente en cualquier sitio con cobertura, a cambio de una cuota recurrente. Los modelos \"sin suscripción\" suelen basarse en Bluetooth o redes de rastreo compartidas (similares a un AirTag): son gratuitos de mantener, pero su alcance depende de que haya otros dispositivos compatibles cerca, lo que los hace menos fiables en zonas poco pobladas.",
        ],
      },
      {
        heading: "Autonomía de batería",
        body: [
          "La autonomía real cae mucho con el uso intensivo del GPS en tiempo real, así que la cifra que anuncia el fabricante en modo de espera casi nunca coincide con el uso diario en exteriores. Si tu mascota pasa muchas horas fuera sin acceso fácil a cargar el collar, prioriza autonomía sobre otras funciones: un GPS con muchas prestaciones pero que dura medio día no sirve de nada si se apaga antes de que puedas localizarla.",
        ],
      },
      {
        heading: "Resistencia al agua y peso del dispositivo",
        body: [
          "Un perro que se moja en cada paseo (lluvia, charcos, playa) necesita al menos resistencia IPX6 o equivalente; revisa la certificación concreta, no solo la palabra \"resistente al agua\" en el anuncio. El peso y tamaño del dispositivo importa especialmente en perros pequeños o gatos: un GPS pensado para razas grandes puede resultar incómodo o directamente inutilizable en un gato o un chihuahua.",
        ],
      },
      {
        heading: "Precisión y zonas seguras (geofencing)",
        body: [
          "La función de zona segura (geofencing) avisa al móvil en cuanto la mascota sale de un área definida en el mapa, y suele ser más útil en el día a día que la localización puntual: avisa del problema en el momento en que empieza, no cuando ya llevas horas buscando. La precisión del GPS puede degradarse en interiores o en zonas urbanas con edificios altos, así que conviene no depender de él como única medida de seguridad frente a escapes (microchip y placa identificativa siguen siendo necesarios).",
        ],
      },
    ],
    checklist: [
      "Con suscripción para cobertura fiable en cualquier zona; sin suscripción solo si hay buena densidad de dispositivos compatibles cerca",
      "Autonomía real con uso intensivo, no solo la cifra de espera del fabricante",
      "Resistencia al agua certificada si la mascota se moja a menudo",
      "Peso y tamaño adecuados si es para un gato o un perro pequeño",
      "Zona segura (geofencing) como aviso temprano, sin sustituir chip y placa",
    ],
    faq: [
      {
        q: "¿Un collar GPS sin suscripción es tan fiable como uno con SIM?",
        a: "No en todos los contextos: los modelos sin suscripción dependen de redes de rastreo compartidas o Bluetooth, así que funcionan mejor en zonas urbanas con mucha densidad de dispositivos compatibles y peor en zonas rurales o poco pobladas. Si necesitas cobertura garantizada en cualquier sitio, un modelo con SIM y suscripción es más fiable, a cambio de una cuota mensual.",
      },
      {
        q: "¿Un collar GPS sustituye al microchip?",
        a: "No, son complementarios: el microchip identifica legalmente a la mascota si la encuentra otra persona o una protectora, pero no da ubicación en tiempo real. El GPS ayuda a localizarla rápido tras un escape, pero no sirve como identificación legal ni funciona si se agota la batería.",
      },
    ],
    products: [
      {
        asin: "B0HGQJB11X",
        title: "Localizador GPS Perros y Gatos, Compatible iOS/Android, Sin Suscripción, IP67",
        note: "Entrada de gama sin cuota mensual, resistencia al agua IP67.",
        img: "https://m.media-amazon.com/images/I/71V0UDclaeL._AC_UL320_.jpg",
        price: "21,99",
        rating: "4,8★",
      },
      {
        asin: "B0H8J76ZQP",
        title: "Localizador GPS Perros y Gatos Sin Suscripción, Collar Ajustable",
        note: "Formato compacto, adecuado también para gatos por su tamaño reducido.",
        img: "https://m.media-amazon.com/images/I/41zhNiP83GL._AC_UL320_.jpg",
        price: "23,46",
        rating: "3,8★",
      },
      {
        asin: "B0H8RZZGM5",
        title: "Molly&Cody GPS Tracker para Perros y Gatos, 4 Modos de Seguimiento",
        note: "Varios modos de seguimiento para ajustar consumo de batería según la situación.",
        img: "https://m.media-amazon.com/images/I/81KMykIhDBL._AC_UL320_.jpg",
        price: "27,99",
        rating: "4,5★",
      },
      {
        asin: "B0HF75VNHN",
        title: "Localizador GPS Perros, Posicionamiento Global en Tiempo Real, Collar Ajustable",
        note: "Posicionamiento en tiempo real, pensado para perros que pasan tiempo sueltos en el campo.",
        img: "https://m.media-amazon.com/images/I/71VPig9bwnL._AC_UL320_.jpg",
        price: "27,99",
        rating: "4,5★",
      },
      {
        asin: "B0H7R7K8LH",
        title: "Collar GPS Perro Flexible y Sin Suscripciones, Seguimiento en Tiempo Real",
        note: "Diseño flexible que se adapta a distintos tamaños de cuello.",
        img: "https://m.media-amazon.com/images/I/71zpa7TvLyL._AC_UL320_.jpg",
        price: "28,99",
        rating: "4,8★",
      },
      {
        asin: "B0HCZD8VSX",
        title: "Collar GPS Gatos 2 en 1, Seguimiento en Tiempo Real y Antipérdida, Sin Suscripción",
        note: "Pensado específicamente para gatos, con función antipérdida además de localización.",
        img: "https://m.media-amazon.com/images/I/81vYd6WcyDL._AC_UL320_.jpg",
        price: "29,99",
        rating: "4,7★",
      },
      {
        asin: "B0H7Y2WVM7",
        title: "Pitpat Localizador GPS Perros Sin Suscripción, 100% Impermeable",
        note: "Gama alta: máxima resistencia al agua de la selección, sin cuota mensual.",
        img: "https://m.media-amazon.com/images/I/818+oWjtpkL._AC_UL320_.jpg",
        price: "199,00",
        rating: "4,6★",
      },
      {
        asin: "B0D6Z4L6BW",
        title: "Tractive GPS para Perros, Edición 2025",
        note: "Marca de referencia con suscripción, cobertura fiable en cualquier zona gracias a los datos móviles.",
        img: "https://m.media-amazon.com/images/I/71il4nMReSL._AC_UL320_.jpg",
        price: "69,00",
        rating: "4,4★",
      },
      {
        asin: "B0G52VQTFR",
        title: "Tractive GPS para Perros Inteligente, Edición 2026",
        note: "Versión más reciente de Tractive, con monitorización de actividad además de localización.",
        img: "https://m.media-amazon.com/images/I/71PgKY4lFzL._AC_UL320_.jpg",
        price: "79,00",
        rating: "4,2★",
      },
      {
        asin: "B0HD67TG23",
        title: "Collar GPS Gatos sin Suscripción, Seguimiento en Tiempo Real",
        note: "Formato compacto sin cuota mensual, pensado específicamente para gatos.",
        img: "https://m.media-amazon.com/images/I/71P7q9dFjSL._AC_UL320_.jpg",
        price: "29,99",
        rating: "5,0★",
      },
      {
        asin: "B0HF38QS46",
        title: "Collar GPS Gatos 2 en 1, Compatible iOS/Android",
        note: "Alternativa sin suscripción con función antipérdida además de localización.",
        img: "https://m.media-amazon.com/images/I/71Dnkr8+M9L._AC_UL320_.jpg",
        price: "21,84",
        rating: "4,4★",
      },
    ],
  },
];

const ARTICLES = [
  {
    slug: "como-montar-el-rincon-perfecto-para-tu-mascota-en-casa",
    title: "Cómo montar el rincón perfecto para tu mascota en casa",
    dek: "Cama, agua, zona de juego: el orden lógico para organizar un espacio propio para tu perro o gato.",
    updated: "2026-09-16",
    img: "/assets/img/blog/como-montar-el-rincon-perfecto-para-tu-mascota-en-casa.jpg",
    body: [
      "Montar un rincón fijo para la mascota ayuda a que asocie ese espacio con calma y descanso, algo especialmente útil en cachorros y gatitos recién llegados a casa, pero también en mascotas adultas que cambian de vivienda.",
      "El orden que mejor funciona suele ser: primero <a href=\"/guias/camas-para-perros.html\">la cama</a>, en una zona tranquila pero no aislada del todo (los animales sociales prefieren descansar cerca de donde está la familia, no en una habitación cerrada); después el agua, en un punto distinto de la comida para fomentar que beban más; y por último la zona de juego o rascado, que puede estar en otro punto de la casa sin problema.",
      "En gatos, añadir altura al rincón (una balda, <a href=\"/guias/rascadores-para-gatos.html\">un árbol rascador con plataforma</a>) aporta mucho valor porque buscan puntos elevados para vigilar su territorio de forma natural. En perros, un límite físico claro (una manta, una alfombra específica) ayuda a que entienda dónde empieza y termina \"su\" espacio.",
      "Evita colocar la cama justo al lado de radiadores o corrientes de aire de puertas y ventanas: la temperatura del rincón influye tanto en el confort como la elección de la cama en sí.",
      "En las guías de este sitio (camas, comederos, <a href=\"/guias/fuentes-de-agua-para-mascotas.html\">fuentes de agua</a>, rascadores y transportines) desarrollamos cada elemento por separado con más detalle de criterios.",
    ],
  },
  {
    slug: "5-errores-comunes-al-elegir-arnes-o-correa",
    title: "5 errores comunes al elegir arnés o correa",
    dek: "Fallos fáciles de evitar que hacen que el arnés o la correa acaben sin usarse o, peor, sean inseguros.",
    updated: "2026-09-14",
    img: "/assets/img/blog/5-errores-comunes-al-elegir-arnes-o-correa.jpg",
    body: [
      "Antes de comprar otro arnés o correa, merece la pena revisar si el problema real está en alguno de estos errores habituales, todos evitables sin gastar más dinero.",
      "1. Guiarse solo por el peso del perro para elegir talla. Dos perros del mismo peso pueden tener contornos de pecho muy distintos según la raza: medir antes de comprar evita casi todos los problemas de ajuste.",
      "2. Comprar <a href=\"/guias/arneses-para-perros.html\">un arnés</a> con la anilla solo en la espalda para un perro que tira mucho. Sin un punto de enganche en el pecho, el efecto antitirones no existe: el arnés en sí no controla nada si el punto de enganche no ayuda a redirigir la fuerza.",
      "3. Elegir <a href=\"/guias/correas-para-perros.html\">una correa extensible</a> como única correa en ciudad. Cerca de tráfico, cruces o aceras estrechas, el mecanismo de frenado tarda demasiado en reaccionar: es más segura como complemento en parques que como correa de uso diario urbano.",
      "4. No comprobar el material de las hebillas. Unas hebillas de plástico fino pueden ceder con un tirón fuerte inesperado; en perros grandes o fuertes conviene revisar que sean de metal o plástico reforzado.",
      "5. Dejar de ajustar el arnés después de la primera vez. El pelaje cambia con las estaciones y el peso del perro puede variar: revisar el ajuste cada pocos meses evita tanto rozaduras como el riesgo de que se suelte.",
    ],
  },
  {
    slug: "cuanto-merece-la-pena-gastar-en-accesorios-para-tu-mascota",
    title: "¿Cuánto merece la pena gastar en accesorios para tu mascota?",
    dek: "Dónde está el salto de calidad real y dónde el precio ya no compra mucho más.",
    updated: "2026-09-12",
    img: "/assets/img/blog/cuanto-merece-la-pena-gastar-en-accesorios-para-tu-mascota.jpg",
    body: [
      "No existe una cifra válida para todo el mundo, pero sí hay tramos de precio donde el salto de calidad es claro y tramos donde ya no se nota tanto, y varían según el tipo de accesorio.",
      "El primer salto importante suele estar entre lo más barato y la gama media: en arneses y <a href=\"/guias/correas-para-perros.html\">correas</a>, ese tramo marca la diferencia entre materiales que se degradan en meses y otros que aguantan años de paseos diarios. En camas, ese salto está en si llevan o no espuma de mayor densidad, algo que se nota especialmente en perros mayores o pesados.",
      "El segundo salto, más caro, aparece en productos con electrónica o mecanismos (<a href=\"/guias/comederos-automaticos-para-mascotas.html\">comederos automáticos</a>, fuentes, areneros autolimpiables, collares GPS): ahí el precio compra sobre todo fiabilidad del mecanismo, control por app más preciso y mejor autonomía de batería, no solo diseño.",
      "A partir de cierto precio, en la mayoría de categorías lo que se paga de más es marca, diseño o accesorios extra, no una mejora real en los criterios que importan (ajuste, seguridad, capacidad, autonomía). Esos criterios básicos suelen estar ya cubiertos en el tramo de precio medio.",
      "La pregunta que más ayuda a decidir no es \"¿cuánto cuesta?\" sino \"¿este accesorio depende de un mecanismo que puede fallar?\". Si la respuesta es sí (comedero automático, GPS, <a href=\"/guias/areneros-autolimpiables-para-gatos.html\">arenero autolimpiable</a>), invertir algo más en fiabilidad suele compensar. Si es un accesorio simple (correa, cama, rascador), el tramo medio ya cubre casi todo lo importante.",
    ],
  },
  {
    slug: "como-preparar-a-tu-mascota-para-viajar-en-coche-o-avion",
    title: "Cómo preparar a tu mascota para viajar en coche o avión",
    dek: "Los pasos previos que reducen el estrés del viaje, además de elegir bien el transportín.",
    updated: "2026-09-10",
    img: "/assets/img/blog/como-preparar-a-tu-mascota-para-viajar-en-coche-o-avion.jpg",
    body: [
      "Viajar con una mascota sale mejor cuando la preparación empieza antes del día del viaje, no cuando ya estás metiendo las maletas en el coche o haciendo la maleta para el aeropuerto.",
      "Para el coche, acostumbrar al perro o gato al <a href=\"/guias/transportines-para-mascotas.html\">transportín</a> en casa, con la puerta abierta y premios dentro, evita que la primera vez que lo vea sea también la primera vez que viaja en él. Trayectos cortos de práctica (una vuelta a la manzana) ayudan a detectar si se marea antes de un viaje largo.",
      "Para el avión, revisar la normativa concreta de la aerolínea con semanas de antelación es imprescindible: las medidas máximas del transportín, si se permite en cabina o solo en bodega, y la documentación sanitaria necesaria varían mucho entre compañías y no siempre coinciden con lo que dice el fabricante del transportín.",
      "En ambos casos, no dar de comer justo antes de salir reduce el riesgo de mareo, aunque sí conviene que beba agua con normalidad. Llevar algo con el olor de casa (una manta, un juguete habitual) dentro del <a href=\"/guias/transportines-para-mascotas.html\">transportín</a> ayuda a que el espacio le resulte menos extraño.",
      "Por último, comprobar que el microchip está actualizado con tu contacto correcto antes de cualquier viaje es una medida de seguridad básica que cuesta cero y que muchas veces se pasa por alto hasta que ya es tarde.",
    ],
  },
  {
    slug: "que-necesita-realmente-un-gatito-o-cachorro-el-primer-mes",
    title: "Qué necesita realmente un gatito o cachorro el primer mes",
    dek: "La lista mínima de verdad, sin comprar de más antes de conocer las costumbres de tu nueva mascota.",
    updated: "2026-09-07",
    img: "/assets/img/blog/que-necesita-realmente-un-gatito-o-cachorro-el-primer-mes.jpg",
    body: [
      "El primer mes con un gatito o un cachorro genera la tentación de comprar todo el catálogo de accesorios de golpe, pero la mayoría de necesidades reales del primer mes son pocas y concretas.",
      "Lo imprescindible desde el primer día: una cama o zona de descanso propia, comederos de comida y agua, y en el caso del gatito, un arenero (mejor de bordes bajos al principio, para que le resulte fácil entrar y salir). En el cachorro, collar con chapa identificativa y, en cuanto complete la pauta de vacunación que indique el veterinario, <a href=\"/guias/arneses-para-perros.html\">un arnés</a> para las primeras salidas.",
      "Lo que puede esperar: transportín de gama alta, torre de gatos grande o <a href=\"/guias/comederos-automaticos-para-mascotas.html\">comedero automático programable</a>. Son compras que tienen más sentido cuando ya conoces las costumbres reales de tu mascota (cuánto come, si tira de la correa, si rasca mucho) en lugar de adivinar antes de convivir con ella.",
      "Un error común es comprar directamente productos de talla \"adulto\": un arnés o <a href=\"/guias/camas-para-perros.html\">una cama</a> pensados para el tamaño final del animal no se ajustan bien a un cachorro o gatito pequeño, así que conviene una talla de transición y cambiar cuando crezca, no comprar de más por adelantado.",
      "Por último, las primeras semanas conviene observar más que comprar: cada gatito o cachorro tiene preferencias distintas (dónde le gusta dormir, si prefiere agua en movimiento, si rasca en horizontal o en vertical), y esa información evita compras que acaban sin usarse.",
    ],
  },
];

// Un producto destacado por categoría, para el bloque "Lo más recomendado"
// que aparece en todas las páginas (ver featuredProductsSection en lib.js).
// Se reutilizan los datos ya cargados en GUIDES para no duplicar imagen/precio.
function pickFeatured(guideSlug, asin) {
  const g = GUIDES.find((x) => x.slug === guideSlug);
  const p = g.products.find((x) => x.asin === asin);
  return { ...p, category: g.slug, categoryTitle: g.title };
}

const FEATURED = [
  pickFeatured("arneses-para-perros", "B01M8JT6FT"),
  pickFeatured("correas-para-perros", "B00O3B2RG2"),
  pickFeatured("comederos-automaticos-para-mascotas", "B0CD7NRW37"),
  pickFeatured("fuentes-de-agua-para-mascotas", "B0B4W8FDBV"),
  pickFeatured("camas-para-perros", "B0GK7YNX6P"),
  pickFeatured("transportines-para-mascotas", "B00OP6SMCI"),
  pickFeatured("areneros-autolimpiables-para-gatos", "B0D9QGW2M6"),
  pickFeatured("rascadores-para-gatos", "B0BN9YL1KH"),
  pickFeatured("juguetes-interactivos-para-perros", "B009WPTW9E"),
  pickFeatured("collares-gps-para-mascotas", "B0HCZD8VSX"),
];

module.exports = { GUIDES, ARTICLES, FEATURED };
